### ISSUE TITLE
Shaders appear no different from vanilla

### ISSUE THREAD

**Issue by sudo-nano** [Null-MC/Arc-Shader#5]
When I enable Arc shaders, it looks no different from vanilla. 

## Hardware
- AMD Ryzen 7 5700X
- AMD Radeon 6700

## Software
- Java 17.0.6 2023-01-17 LTS
- Prism Launcher 6.3

## Game and Mods
- Minecraft 1.19.3
- Arc 0.15.2 Shaders
- Patrix 1.19.3 32x Basic Resource Pack
- badpackets-fabric-0.3.4.jar
- fabric-api-0.75.1+1.19.3.jar
- indium-1.0.14+mc1.19.3.jar
- iris-mc1.19.3-1.5.2.jar
- journeymap-1.19.3-5.9.3-fabric.jar
- lithium-fabric-mc1.19.3-0.10.4.jar
- memoryleakfix-1.19.3-0.7.0.jar
- phosphor-fabric-mc1.19.x-0.8.1.jar
- sodium-fabric-mc1.19.3-0.4.9+build.23.jar
- wthit-fabric-6.1.4.jar

## Screenshots
![2023-04-12_22 39 47](https://user-images.githubusercontent.com/63484662/231665957-dd14b875-5a8d-413d-b216-01771a16e7d5.png)
![2023-04-12_22 39 36](https://user-images.githubusercontent.com/63484662/231665966-6c9cbf7d-89c7-479d-858e-1b6941e45dfb.png)

**Comment by null511** [comment]
You need Iris 1.6.0 for "ultra" features, which includes colored lighting and cascaded shadow mapping.
Also "ultra" is just everything at max and not meant to be used...

**Comment by null511** [comment]
Also, you need Continuity & Indium for Patrix CTM, and colormatic for tinted blocks like concrete, terracotta, etc

**Comment by sudo-nano** [comment]
I see, thanks. I'll make the recommended changes and post an update here. Also worth noting that there's no Iris 1.6 or higher for Minecraft 1.9.3, so I'll have to try it with 1.9.4.

**Comment by sudo-nano** [comment]
After setting up a new instance to fulfill these parameters, the shaders are still not working. 

## Game and Mods
- Minecraft 1.19.4
- Quilt 0.18.10 (You recommended colormatic, and colormatic requires Quilt instead of Fabric)
- continuity-3.0.0-beta.2+1.19.3.jar
- indium-1.0.15+mc1.19.4.jar
- iris-mc1.19.4-1.6.1.jar
- lithium-fabric-mc1.19.4-0.11.1.jar
- phosphor-fabric-mc1.19.x-0.8.1.jar
- qfapi-6.0.0-beta.3_qsl-5.0.0-beta.2_fapi-0.76.0_mc-1.19.4.jar
- reeses_sodium_options-1.5.0+mc1.19.4-build.72.jar
- sodium-extra-0.4.18+mc1.19.4-build.100.jar
- sodium-fabric-mc1.19.4-0.4.10+build.24.jar

## Screenshots
Shaders are enabled in the below screenshots. 
![2023-04-17_20 09 33](https://user-images.githubusercontent.com/63484662/232661946-e083d75f-5175-4d53-8f02-7d89cfa1d5f9.png)
![2023-04-17_20 09 22](https://user-images.githubusercontent.com/63484662/232661948-818ed471-01d9-410a-9c02-f50ce9909b7b.png)


I don't understand why Ultra is an option if it's not meant to be used. Additionally, Iris 1.6.0 or higher is only available for Minecraft 1.19.4, but the Patrix resource pack is only available up to 1.19.3. In the above screenshots, I used Patrix 1.19.3 on Minecraft 1.19.4, since no newer version was available. 

Is the fact that the recommended resource pack (Patrix) isn't available for the only version of Minecraft supporting the necessary Iris version an oversight or intentional?

**Comment by null511** [comment]
1.19.3 resource packs work fine on 1.19.4 so that's not really a concern. You can use any resource pack though, I just like & recommend Patrix. As for Colormatic, that's also only needed for Patrix (or any other RP using color-tint feature) and not specific to Arc.

As for why ultra profile isn't working, I can't diagnose anything without an error log (found in ~/.minecraft/logs/latest.txt). When Arc was last released, Iris was still in beta and might be broken with the latest public release.

**Comment by sudo-nano** [comment]
Examination of `latest.log` shows that the shader failed to compile. 

```
[20:00:18] [Render thread/WARN]: Shader compilation log for final.fsh: ERROR: 0:193: 'texel offset' : argument must be compile-time constant 
ERROR: 0:193: '=' :  cannot convert from ' global 4-component vector of float' to ' temp float'
ERROR: 0:193: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.


[20:00:18] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
net.coderbot.iris.gl.shader.ShaderCompileException: final.fsh: ERROR: 0:193: 'texel offset' : argument must be compile-time constant 
ERROR: 0:193: '=' :  cannot convert from ' global 4-component vector of float' to ' temp float'
ERROR: 0:193: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.


	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:46) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:25) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:100) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:53) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.postprocess.FinalPassRenderer.createProgram(FinalPassRenderer.java:353) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.postprocess.FinalPassRenderer.lambda$new$0(FinalPassRenderer.java:101) ~[transformed-mod-iris.i0:0/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.coderbot.iris.postprocess.FinalPassRenderer.<init>(FinalPassRenderer.java:97) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:316) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:674) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[transformed-mod-iris.i0:0/:?]
	at net.minecraft.class_761.handler$zcn000$iris$beginLevelRender(class_761.java:5458) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_761.method_22710(class_761.java:1232) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_757.method_3188(class_757.java:1100) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_757.method_3192(class_757.java:872) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1218) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527) ~[quilt-loader-0.18.10.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.18.10.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.18.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

**Comment by null511** [comment]
I'm assuming you've been using the latest release; I'm pretty sure that's a bug with FXAA that is now fixed in the latest in-dev release on github: https://github.com/Null-MC/Arc-Shader/archive/refs/heads/main.zip

**Comment by sudo-nano** [comment]
Thanks, that's almost entirely fixed it! Now the only thing that's broken is the water. 

## Screenshots
This is what it looks like on "Vanilla" material settings.
![2023-04-17_20 39 21](https://user-images.githubusercontent.com/63484662/232665809-e105efb4-c259-4c31-8618-31914ce29ac6.png)

This is what it looks like on "Patrix" material settings
![2023-04-17_20 40 41](https://user-images.githubusercontent.com/63484662/232665890-bd044130-d667-4229-8179-7ceb95fc0474.png)

This is what it looks like on "Lab PBR" material settings.
![2023-04-17_20 41 55](https://user-images.githubusercontent.com/63484662/232665967-a7a6eeaa-831d-499e-bdad-49e39c415a55.png)

**Comment by null511** [comment]
That is an unfortunate bug with the new AMD drivers. I haven't been able to identify exactly what causes it (since I don't have AMD GPU to test with), but I know it should be fine with version `22.5.1`

**Comment by sudo-nano** [comment]
Good to know. If there are any tests that I could help you run, I'd be happy to do so.

**Comment by sudo-nano** [comment]
Here's my latest.log from the last run where I took the buggy water photos. 
[latest-sanitized.log](https://github.com/Null-MC/Arc-Shader/files/11258713/latest-sanitized.log)
